server:
  port: 8001


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guli?useUnicode=true&characterEncoding=utf8&useSSL=false&serveratimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    com.atguigu.edu.mapper: debug





#
#mybatis-plus:
#  global-config:
#    db-config:
#      sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
